# 配置文件请严格遵循yaml语法格式，yaml学习地址:
#  https://ansible-tran.readthedocs.io/en/latest/docs/YAMLSyntax.html
#  http://einverne.github.io/post/2015/08/yaml.html

# 定时时间、
alarm_timed: '8:30'

# 格言渠道
# 1 : ONE●一个
# 2 : 词霸（每日英语）
dictum_channel: 1

# 图片渠道
# 1 : ONE●一个
# 2： Bing壁纸
img_channel: 1

girlfriend_infos:
  -
    #女友微信号
    wechat_name: 'ohohohmydear!'
    #女友所在地
    city_name: '北京'
    # 从那天开始勾搭的（可空）
    start_date: '2014-07-10'
    # 短句的最后留言（可空）
    sweet_words: '专属大猪蹄子'

  #如果有你多个人需要发送，则参照这个样式，复制即可
  # -
  #   wechat_name: '陈老师'
  #   city_name: '朝阳区'
  #   start_date: '2018-11-11'
  #   sweet_words: '来自你俊美的老公。'



